# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_lahir', models.DateField()),
                ('jk', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('user_type', models.CharField(choices=[('1', 'Pemilik'), ('2', 'Pengurus'), ('3', 'Penghuni')], default='3', max_length=1)),
                ('n_login', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
