# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profil_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='tanggal_lahir',
        ),
        migrations.AddField(
            model_name='profil',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
