# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170804_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='instansi',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profesi',
            field=models.CharField(choices=[('PNS', 'Pegawai Negri'), ('PSW', 'Pegawai Swasta'), ('PDG', 'Pedagang'), ('PSH', 'Pengusaha'), ('DRV', 'Driver'), ('MHS', 'Mahasiswa')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='n_login',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profil',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
