# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170804_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.FileField(default='media_root/user-icon.jpg', upload_to='media_root/'),
        ),
    ]
