# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170805_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(default='user-icon.jpg', upload_to='media/'),
        ),
    ]
