# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulasan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='tgl_balas',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
