# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas', models.CharField(max_length=7)),
                ('listrik', models.CharField(max_length=1)),
                ('air', models.CharField(max_length=1)),
                ('wifi', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('parkir', models.CharField(max_length=1)),
                ('kamar_mandi', models.CharField(max_length=1)),
                ('kloset', models.CharField(max_length=1)),
                ('dapur', models.CharField(max_length=1)),
                ('pasar', models.BooleanField(default=False)),
                ('rumah_sakit', models.BooleanField(default=False)),
                ('rumah_makan', models.BooleanField(default=False)),
                ('mini_market', models.BooleanField(default=False)),
                ('kontrakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrakan.ProfilKontrakan')),
            ],
        ),
    ]
