# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0002_fasilitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='gerbang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='pagar_kawat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='satpam',
            field=models.BooleanField(default=False),
        ),
    ]
