# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0004_auto_20170809_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrasi',
            name='biaya_elektronik',
        ),
        migrations.RemoveField(
            model_name='administrasi',
            name='biaya_elektronik_currency',
        ),
        migrations.AddField(
            model_name='administrasi',
            name='biaya_lain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
