# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0007_administrasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoKontrakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='kontrakan/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('foto_utama', models.BooleanField(default=False)),
                ('kontrakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrakan.ProfilKontrakan')),
            ],
        ),
    ]
