# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0008_fotokontrakan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilkontrakan',
            name='n_unit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profilkontrakan',
            name='subkat',
            field=models.CharField(choices=[('RMH', 'Rumah'), ('PTK', 'Petakan')], max_length=5),
        ),
    ]
