# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0009_auto_20170812_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilkontrakan',
            name='id_kont',
        ),
    ]
