# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0011_auto_20170812_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasilitas',
            name='pagar_kawat',
        ),
    ]
