# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0012_remove_fasilitas_pagar_kawat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasilitas',
            name='kamar_mandi',
        ),
        migrations.RemoveField(
            model_name='fasilitas',
            name='kloset',
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='jemuran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='kamar_mandi_dalam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='kamar_mandi_luar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='kasur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='kloset_duduk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='kloset_jongkok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='lemari',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='wastafel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fasilitas',
            name='dapur',
            field=models.BooleanField(default=False),
        ),
    ]
