# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0013_auto_20170812_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilkontrakan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
