# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0014_profilkontrakan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas',
            name='akses_tol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='mall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='stasiun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fasilitas',
            name='terminal_bus',
            field=models.BooleanField(default=False),
        ),
    ]
