# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0015_auto_20170814_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilkontrakan',
            name='subkat',
        ),
        migrations.AlterField(
            model_name='profilkontrakan',
            name='status',
            field=models.CharField(choices=[('1', 'Sedang Dibangun'), ('2', 'Siap Huni'), ('3', 'Sedang Renovasi')], default='2', max_length=1),
        ),
    ]
