# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0017_auto_20170814_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilkontrakan',
            name='dilihat',
            field=models.IntegerField(default=0),
        ),
    ]
