# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0018_profilkontrakan_dilihat'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontarkanViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kontrakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrakan.ProfilKontrakan')),
            ],
        ),
    ]
