# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0019_kontarkanviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilkontrakan',
            old_name='modified',
            new_name='diupdate',
        ),
    ]
