# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0021_auto_20170818_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='penghuni',
            name='konfirm',
            field=models.BooleanField(default=False),
        ),
    ]
