# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0022_penghuni_konfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='penghuni',
            name='pasutri',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='penghuni',
            name='tanggal_masuk',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
