# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0023_auto_20170820_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penghuni',
            name='n_penghuni',
        ),
        migrations.RemoveField(
            model_name='penghuni',
            name='pasutri',
        ),
    ]
