# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kontrakan', '0025_auto_20170823_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_kontrakan', models.BooleanField(default=False)),
                ('konfirm_penghuni', models.BooleanField(default=False)),
                ('galeri', models.BooleanField(default=False)),
                ('ulasan', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
