# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0026_pengurus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='kontrakan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kontrakan.ProfilKontrakan'),
        ),
        migrations.AlterField(
            model_name='pengurus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
