# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0028_pengurus_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilkontrakan',
            name='diupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
