# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrakan', '0030_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='penghuni',
            name='ket',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
